### ISSUE TITLE
Casting doesn't work for anonymous objectsI think

### ISSUE THREAD

**Issue by ceddlyburge** [ProxyFoo/ProxyFoo#11]
This code throws a runtime error for me, and I think it wouldn't if anonymouse objects were supported:

    public interface IPreliminaries
    {
        double Total { get; }
        double ContractorPreliminaries { get; }
        double OverrunCosts { get; }
        double ContractorOverheadAndProfit { get; }
    }

    ...

    blackboard.PreliminariesCosts = Duck.Cast<IPreliminaries>(
                new
                {
                    ContractorPreliminaries = constructorPreliminaries,
                    OverrunCosts = overrunCosts,
                    ContractorOverheadAndProfit = contractorOverheadAndProfit,
                    Total = total
                });

**Comment by jdasilva** [comment]
It's throwing a TypeAccessException because it turns out that C# anonymous types are internal.  I found this [article](http://www.heartysoft.com/ashic/blog/2010/5/anonymous-types-c-sharp-4-dynamic) that talked about it.  The good news is that you can work around this by using [assembly: InternalsVisibleTo("ProxyFoo.Dynamic")] in the assembly where you are creating the anonymous types.
